### ISSUE TITLE
RecipeController: Exception beim Erstellen eines Rezeptes

### ISSUE THREAD

**Issue by patrick246** [INF16A/kochbuch#66]
org.springframework.web.bind.ServletRequestBindingException
Missing request header 'principal' for method parameter of type Principal

Das liegt daran, dass im RecipeController in der Zeile 96 eine `@RequestHeader` Annotation vor dem Principal steht und Spring natürlich diesen Header nicht finden kann. Wenn man diese Annotation entfernt funktioniert der Aufruf

**Comment by hoernerth** [comment]
fixed PR #68
